# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin
pool:
  vmImage: 'macOS-10.13' # For Windows, use 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_4_1
  displayName: 'Select Xamarin SDK version'

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamariniOS@2
  inputs:
    solutionFile: '**/*iOS.csproj'
    configuration: '$(buildConfiguration)'
    packageApp: false
    buildForSimulator: true